services:
  postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=webzma
      - POSTGRES_PASSWORD=webzma123
      - POSTGRES_DB=fundacite_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
volumes:
  postgres_data:
